name: NodeJs DevSecOps Pipeline

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Application Dependencies
        run: npm install

      - name: SonarCloud Scan (SAST)
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dotnetgithubactionsorg
            -Dsonar.projectKey=dotnetgithubactionsproject

  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run the SCA scan
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Snyk Open Source Scan (SCA)
        uses: snyk/actions/node@v0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST scan on Web App
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://example.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
